---
- name: Remove downloaded repositories
  file:
    path: "{{ nginx_download_dir }}/{{ item.key }}"
    state: absent
  loop: "{{ query('dict', nginx_dynamic_modules) }}"

- name: Remove Nginx source packages
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ nginx_download_dir }}/{{ nginx_package }}-{{ nginx_version_raw.stdout }}-1+xenial0.debian.tar.xz"
    - "{{ nginx_download_dir }}/{{ nginx_package }}-{{ nginx_version_raw.stdout }}-1+xenial0.dsc"
    - "{{ nginx_download_dir }}/{{ nginx_package }}-{{ nginx_version_raw.stdout }}.orig.tar.gz"
