---
- include_tasks: install/prerequisite.yml
  vars:
    state: present

- include_tasks: install/nginx.yml

- include_tasks: install/prerequisite.yml
  vars:
    state: absent
  when: ansible_connection == 'docker'

- name: Include cleanup specific to this role
  include_tasks: cleanup.yml
  when: ansible_connection == 'docker' and not_dev

- name: Import generic cleanup role
  import_role:
    name: cleanup
  when: ansible_connection == 'docker' and not_dev
