---
- name: Find Nginx version
  shell: nginx -v 2>&1 | awk -F/ '{print $2}'
  changed_when: false
  register: nginx_version_raw

- name: Find Nginx configure options
  shell: "nginx -V 2>&1 | awk -F: '$1==\"configure arguments\"{print $2;exit;}'"
  changed_when: false
  register: nginx_configure_options_raw

- name: Set Fact -- Nginx dynamic modules
  set_fact:
    nginx_source_path: "{{ nginx_download_dir }}/{{ nginx_package }}-{{ nginx_version_raw.stdout }}"
    nginx_configure_options: "{{ nginx_configure_options_raw.stdout.split(' --')|reject('search','add-dynamic-module=')|list|join(' --') }}"

- name: Grab Nginx source
  command: "apt-get source {{ nginx_package }}"
  args:
    chdir: "{{ nginx_download_dir }}"
    creates: "{{ nginx_download_dir }}/{{ nginx_package }}-{{ nginx_version_raw.stdout }}"

- name: Grab dynamic module sources
  git:
    repo: "{{ item.value.repo }}"
    dest: "{{ nginx_download_dir }}/{{ item.key }}"
    version: "{{ item.value.version | default(omit) }}"
    force: true
  loop: "{{ query('dict', nginx_dynamic_modules) }}"
  register: nginx_dynamic_module_sources

- name: Get psol download url
  command: bash scripts/format_binary_url.sh PSOL_BINARY_URL
  args:
    chdir: "{{ nginx_download_dir }}/ngx_pagespeed"
  changed_when: false
  register: nginx_psol_download_url

- name: Download and unpack psol
  unarchive:
    src: "{{ nginx_psol_download_url.stdout }}"
    dest: "{{ nginx_download_dir }}/ngx_pagespeed/"
    remote_src: true

- name: Configure dynamic modules
  command: "./configure {{ nginx_configure_options }} --add-dynamic-module=../{{ nginx_dynamic_modules.keys()|join(' --add-dynamic-module=../') }}"
  args:
    chdir: "{{ nginx_source_path }}"
    creates: "{{ nginx_source_path }}/Makefile"

- debug: var=nginx_dynamic_modules.0.objs.0

- name: Compile dynamic modules
  command: make modules
  args:
    chdir: "{{ nginx_source_path }}"
    creates: nginx_dynamic_modules.0.objs.0

- name: Create 60-dynamic-modules.conf
  template:
    src: dynamic-modules.conf.j2
    dest: "{{ nginx_path }}/modules-available/60-dynamic-modules.conf"
